/// <reference types="next" />
/// <reference types="next/image-types/global" />

// Generated by Next. Committed on purpose (see tsconfig.json `include`): it carries the
// ambient `*.css` module declaration that app/layout.tsx's `import './globals.css'` needs,
// so a cold `tsc -b` on a fresh clone typechecks BEFORE anyone has run `next dev`.
// Do not edit — `next dev` / `next build` rewrite it verbatim.
