import {
  CONTRAST_CONTRACT,
  RAMP_FAMILIES,
  RAMP_STEPS,
  ramps,
  SEMANTIC_TOKENS,
  THEME_NAMES,
  themes,
} from './color'
import { ELEVATIONS, elevation } from './elevation'
import { DURATIONS, duration, EASINGS, easing, PRESS_SCALE } from './motion'
import { contrastOf, inSrgbGamut, oklchToHex, oklchToLinearSrgb } from './oklch'
import { RADIUS_FULL, RADIUS_STEPS, radius } from './radius'
import { ICON_SIZES, iconSize, MIN_TOUCH_TARGET, SPACE_STEPS, SPACE_UNIT, space } from './space'
import {
  FONT_SCALE_CAPS,
  FONT_WEIGHTS,
  fontScaleCap,
  fontWeight,
  TYPE_STEPS,
  typeScale,
} from './typography'

// The two platform adapters, as PURE STRING FUNCTIONS.
//
// Keeping the rendering here — rather than inside scripts/gen.mjs — is what makes
// the freshness check a unit test instead of a subprocess: the test calls
// renderWebCss() and compares it to the bytes committed at src/generated/web.css.
// A generator that can only be exercised by spawning a CLI gets tested once, in CI,
// on a good day.
//
// Determinism is structural, not hoped for: every loop walks a canonical ORDER array
// exported by the token modules (RAMP_STEPS, SEMANTIC_TOKENS, TYPE_STEPS, …), never
// Object.keys(). Object key order happens to be stable for these shapes today; the
// day someone adds a computed key it would stop being, and the regen-diff would fire
// on a change nobody made.

const NEWLINE = '\n'

/** Web renders the unitless ramp as rem against a 16px root; native uses dp directly. */
const REM_BASIS = 16

function rem(px: number): string {
  return `${px / REM_BASIS}rem`
}

function cssOklch({ l, c, h }: { l: number; c: number; h: number }): string {
  return `oklch(${l} ${c} ${h})`
}

/**
 * Fail-closed preflight, run before EITHER artifact is emitted.
 *
 * Two invariants, and both must hold in both themes before a single byte is
 * written: every ramp value is inside the sRGB gamut, and every declared contrast
 * pair clears its minimum. Checking after emission — or only in a gate — means a
 * retune that breaks readability still lands in the tree and gets found later by
 * whoever is unlucky.
 */
export function assertTokenContract(): void {
  const failures: string[] = []

  for (const family of RAMP_FAMILIES) {
    for (const step of RAMP_STEPS) {
      const color = ramps[family][step]
      if (!inSrgbGamut(oklchToLinearSrgb(color))) {
        failures.push(
          `${family}.${step} = oklch(${color.l} ${color.c} ${color.h}) is outside the sRGB gamut`,
        )
      }
    }
  }

  for (const theme of THEME_NAMES) {
    for (const pair of CONTRAST_CONTRACT) {
      const ratio = contrastOf(themes[theme][pair.fg], themes[theme][pair.bg])
      if (ratio < pair.min) {
        failures.push(`${theme}: ${pair.fg}/${pair.bg} = ${ratio.toFixed(2)} < ${pair.min}`)
      }
    }
  }

  if (failures.length > 0) {
    throw new Error(`design-token contract violated:\n  ${failures.join('\n  ')}`)
  }
}

// ── web: Tailwind v4, CSS-first ────────────────────────────────────────────────

const WEB_HEADER = [
  '/* GENERATED by packages/design-tokens/scripts/gen.mjs — do not edit.',
  ' *',
  ' * Source of truth: the TypeScript token modules in packages/design-tokens/src.',
  ' * Regenerate with `pnpm --filter @app/design-tokens run gen`; `gen:check` is the',
  ' * regen-diff, so a hand edit here is a red gate, not a design change.',
  ' *',
  ' * Tailwind v4 is CSS-first: there is no tailwind.config.js on the web side, and',
  ' * this @theme block IS the theme. Import it after Tailwind itself:',
  ' *',
  ' *   @import "tailwindcss";',
  ' *   @import "@app/design-tokens/web.css";',
  ' *',
  ' * Plain `@theme`, NOT `@theme inline`: inline substitutes each value into the',
  ' * generated utilities, which would freeze every color at its light-theme value and',
  ' * make the dark override below do nothing. Plain @theme emits real custom',
  ' * properties that the cascade can still override.',
  ' *',
  ' * The neutral/accent/danger/success ramps deliberately REPLACE the same-named',
  ' * Tailwind defaults, so `bg-neutral-900` cannot quietly paint an untokenized grey',
  ' * next to a `bg-surface`.',
  ' */',
  '',
]

function emitWebRamps(lines: string[]): void {
  for (const family of RAMP_FAMILIES) {
    lines.push(`  /* ${family} ramp */`)
    for (const step of RAMP_STEPS) {
      lines.push(`  --color-${family}-${step}: ${cssOklch(ramps[family][step])};`)
    }
    lines.push('')
  }
}

function emitWebSemantic(lines: string[]): void {
  lines.push(
    '  /* Semantic tokens — LIGHT is the @theme default. */',
    '  /* The dark values are applied by the override blocks below, so a component */',
    '  /* only ever names the role, never the theme. */',
  )
  for (const token of SEMANTIC_TOKENS) {
    lines.push(`  --color-${token}: ${cssOklch(themes.light[token])};`)
  }
  lines.push('')
}

function emitWebScales(lines: string[]): void {
  lines.push(
    '  /* One base unit; Tailwind derives its whole dynamic spacing scale from it, */',
    `  /* so p-4 measures ${space[4]}px exactly as space[4] says it does. */`,
    `  --spacing: ${rem(SPACE_UNIT)};`,
    '',
    '  /* Structural sizes. No Tailwind namespace owns these, so they stay plain */',
    '  /* variables and components reach them as min-h-[var(--size-touch-min)]. */',
  )
  for (const size of ICON_SIZES) {
    lines.push(`  --size-icon-${size}: ${rem(iconSize[size])};`)
  }
  lines.push(`  --size-touch-min: ${rem(MIN_TOUCH_TARGET)};`, '')

  lines.push('  /* Radii. `full` is the pill sentinel, in the form CSS wants. */')
  for (const step of RADIUS_STEPS) {
    const value = radius[step] === RADIUS_FULL ? 'calc(infinity * 1px)' : rem(radius[step])
    lines.push(`  --radius-${step}: ${value};`)
  }
  lines.push('')

  lines.push('  /* Type ramp — size and its bound line height, never one without the other. */')
  for (const step of TYPE_STEPS) {
    lines.push(
      `  --text-${step}: ${rem(typeScale[step].fontSize)};`,
      `  --text-${step}--line-height: ${rem(typeScale[step].lineHeight)};`,
    )
  }
  lines.push('')

  lines.push('  /* Weights. */')
  for (const weight of FONT_WEIGHTS) {
    lines.push(`  --font-weight-${weight}: ${fontWeight[weight]};`)
  }
  lines.push('')

  lines.push('  /* Easing curves. */')
  for (const name of EASINGS) {
    lines.push(`  --ease-${name}: cubic-bezier(${easing[name].join(', ')});`)
  }
  lines.push('')

  lines.push(
    '  /* Elevation. Always black at the declared alpha, in BOTH themes: a tinted */',
    '  /* shadow disappears on a dark canvas, so a component leaning on one would */',
    '  /* silently lose its elevation in exactly one theme. */',
  )
  for (const name of ELEVATIONS) {
    const { offsetY, blur, opacity } = elevation[name]
    lines.push(`  --shadow-${name}: 0 ${offsetY}px ${blur}px rgb(0 0 0 / ${opacity});`)
  }
}

function emitWebRootBlock(lines: string[]): void {
  lines.push(
    '',
    '/* Durations sit outside @theme: Tailwind v4 has no duration theme namespace, so */',
    '/* these stay plain custom properties, read as var(--duration-fast) by a */',
    '/* transition utility. color-scheme is what makes UA form controls, scrollbars */',
    '/* and the default page background follow the theme instead of staying */',
    '/* stubbornly light under a dark canvas. */',
    ':root {',
    '  color-scheme: light dark;',
  )
  for (const name of DURATIONS) {
    lines.push(`  --duration-${name}: ${duration[name]}ms;`)
  }
  lines.push(`  --press-scale: ${PRESS_SCALE};`, '}')
}

function emitWebDarkOverrides(lines: string[]): void {
  const dark = SEMANTIC_TOKENS.map((token) => `--color-${token}: ${cssOklch(themes.dark[token])};`)

  lines.push(
    '',
    '/* Dark, twice, and the pair IS the theming mechanism. */',
    '/* 1. the media query is the DEFAULT: a first paint with no JavaScript, no */',
    '/*    hydration flash and no cookie already respects the OS setting; */',
    '/* 2. [data-theme] is the explicit user OVERRIDE. The :not() on the media */',
    '/*    selector is what lets a user who chose light STAY light under a dark OS — */',
    '/*    without it the media block wins on specificity and the choice silently */',
    '/*    does nothing at night. */',
    '@media (prefers-color-scheme: dark) {',
    '  :root:not([data-theme="light"]) {',
  )
  for (const declaration of dark) {
    lines.push(`    ${declaration}`)
  }
  lines.push('  }', '}', '', '[data-theme="dark"] {')
  for (const declaration of dark) {
    lines.push(`  ${declaration}`)
  }
  lines.push('}')
}

/** The committed bytes of src/generated/web.css. Pure: same input, same string. */
export function renderWebCss(): string {
  assertTokenContract()
  const lines = [...WEB_HEADER, '@theme {']
  emitWebRamps(lines)
  emitWebSemantic(lines)
  emitWebScales(lines)
  lines.push('}')
  emitWebRootBlock(lines)
  emitWebDarkOverrides(lines)
  return `${lines.join(NEWLINE)}${NEWLINE}`
}

// ── native: the resolved theme object ──────────────────────────────────────────

const NATIVE_HEADER = [
  '// GENERATED by packages/design-tokens/scripts/gen.mjs — do not edit.',
  '//',
  '// Source of truth: the TypeScript token modules in packages/design-tokens/src.',
  '// Regenerate with `pnpm --filter @app/design-tokens run gen`; `gen:check` is the',
  '// regen-diff, so a hand edit here is a red gate, not a design change.',
  '//',
  "// Hex, not oklch(): React Native's color parser understands hex/rgb()/named colors",
  '// and has no OKLCH support and no gamut mapping. The conversion therefore happens',
  '// at generate time, against the same CSS Color 4 reference math the web values are',
  '// declared in, and an out-of-gamut ramp value FAILS the generator instead of being',
  '// clamped — a clamped color would paint differently on mobile than the browser',
  '// paints from the identical token, which is the exact divergence this package exists',
  '// to prevent.',
  '',
]

// Quote a key only when it is not a bare TS identifier ('ink-muted', '2xl'). Biome
// formats object keys `asNeeded`, so emitting an unnecessary quote would be stripped
// on the next format pass and read as regen drift.
function tsKey(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) || /^\d+$/.test(name) ? name : `'${name}'`
}

function emitNativeRamps(lines: string[]): void {
  lines.push('export const ramps = {')
  for (const family of RAMP_FAMILIES) {
    lines.push(`  ${family}: {`)
    for (const step of RAMP_STEPS) {
      lines.push(`    ${step}: '${oklchToHex(ramps[family][step])}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const', '')
}

function emitNativePalettes(lines: string[]): void {
  lines.push(
    '/** Resolved per-theme token sets. `dark` is the design base and the launch frame. */',
    'export const palettes = {',
  )
  for (const theme of THEME_NAMES) {
    lines.push(`  ${theme}: {`)
    for (const token of SEMANTIC_TOKENS) {
      lines.push(`    ${tsKey(token)}: '${oklchToHex(themes[theme][token])}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const', '')
}

function emitNativeScales(lines: string[]): void {
  lines.push(
    '/** The base spacing unit (dp). Every value in `space` is a whole multiple of it. */',
    `export const spaceUnit = ${SPACE_UNIT}`,
    '',
    '/** Spacing ramp in dp — the same step names the source uses, with no rem step. */',
    'export const space = {',
  )
  for (const step of SPACE_STEPS) {
    lines.push(`  ${step}: ${space[step]},`)
  }
  lines.push('} as const', '')

  lines.push('export const iconSize = {')
  for (const size of ICON_SIZES) {
    lines.push(`  ${size}: ${iconSize[size]},`)
  }
  lines.push('} as const', '')

  lines.push(
    '/** The 44dp floor every touchable must meet, by hit-slop if not by its visible box. */',
    `export const minTouchTarget = ${MIN_TOUCH_TARGET}`,
    '',
    'export const typeScale = {',
  )
  for (const step of TYPE_STEPS) {
    const { fontSize, lineHeight } = typeScale[step]
    lines.push(`  ${tsKey(step)}: { fontSize: ${fontSize}, lineHeight: ${lineHeight} },`)
  }
  lines.push('} as const', '')

  lines.push(
    "// Strings, not numbers: React Native types TextStyle['fontWeight'] as a string",
    '// union, so numeric weights would force a cast at every call site.',
    'export const fontWeight = {',
  )
  for (const weight of FONT_WEIGHTS) {
    lines.push(`  ${weight}: '${fontWeight[weight]}',`)
  }
  lines.push('} as const', '')

  lines.push(
    '/** maxFontSizeMultiplier caps: OS text scaling is honoured up to these factors. */',
    'export const fontScaleCap = {',
  )
  for (const role of FONT_SCALE_CAPS) {
    lines.push(`  ${role}: ${fontScaleCap[role]},`)
  }
  lines.push('} as const', '')

  lines.push('export const radius = {')
  for (const step of RADIUS_STEPS) {
    lines.push(`  ${step}: ${radius[step]},`)
  }
  lines.push('} as const', '')
}

// Ready-to-spread RN style objects, not the raw design intent: React Native needs four
// iOS keys plus one Android key, so resolving the intent HERE is what keeps the shadow*
// vocabulary out of every component that wants a raised surface.
function emitNativeElevation(lines: string[]): void {
  lines.push(
    '/** Spread one onto a surface style ({ ...elevation.raised }); iOS + Android in one. */',
    'export const elevation = {',
  )
  for (const name of ELEVATIONS) {
    const level = elevation[name]
    lines.push(
      `  ${name}: {`,
      "    shadowColor: '#000000',",
      `    shadowOffset: { width: 0, height: ${level.offsetY} },`,
      `    shadowOpacity: ${level.opacity},`,
      `    shadowRadius: ${level.blur},`,
      `    elevation: ${level.android},`,
      '  },',
    )
  }
  lines.push('} as const', '')
}

function emitNativeMotion(lines: string[]): void {
  lines.push('export const motion = {', '  duration: {')
  for (const name of DURATIONS) {
    lines.push(`    ${name}: ${duration[name]},`)
  }
  lines.push('  },', '  easing: {')
  for (const name of EASINGS) {
    lines.push(`    ${name}: [${easing[name].join(', ')}],`)
  }
  lines.push('  },', `  pressScale: ${PRESS_SCALE},`, '} as const', '')
}

/** The committed bytes of src/generated/native.ts. Pure: same input, same string. */
export function renderNativeModule(): string {
  assertTokenContract()
  const lines = [...NATIVE_HEADER]
  emitNativeRamps(lines)
  emitNativePalettes(lines)
  emitNativeScales(lines)
  emitNativeElevation(lines)
  emitNativeMotion(lines)
  lines.push(
    'export type ThemeName = keyof typeof palettes',
    "export type TokenName = keyof (typeof palettes)['dark']",
    "/** One theme's token set, widened to plain strings for style factories. */",
    'export type Palette = Readonly<Record<TokenName, string>>',
  )
  return `${lines.join(NEWLINE)}${NEWLINE}`
}

/** What the generator writes, keyed by path relative to the package root. */
export const GENERATED_FILES: Readonly<Record<string, () => string>> = {
  'src/generated/web.css': renderWebCss,
  'src/generated/native.ts': renderNativeModule,
}
