// GENERATED by tools/gen-web-routes.mjs — DO NOT EDIT. Run `pnpm gen` and commit the diff.
//
// Every user-reachable page under apps/web/app registers here. `path` and `file` are DERIVED
// from the App Router's file tree, so this registry cannot lie about where a page lives; the
// id, the title key and the three data-state test ids come from the `page.meta.ts` beside each
// `page.tsx`. The `route-manifest` gate closes the loop both ways — a page with no meta and no
// reviewed chrome entry in tools/web-route-allowlist.json fails validate, and a meta naming a
// page that no longer exists fails too.
import { meta as notesMeta } from '../app/(protected)/o/[orgSlug]/notes/page.meta'
import { meta as orgsMeta } from '../app/(protected)/o/page.meta'
import { meta as securityMeta } from '../app/(protected)/security/page.meta'
import type { WebRouteEntry } from './routes'

export const WEB_ROUTES = [
  {
    ...orgsMeta,
    file: '(protected)/o/page',
    path: '/o',
  },
  {
    ...notesMeta,
    file: '(protected)/o/[orgSlug]/notes/page',
    path: '/o/:orgSlug/notes',
  },
  {
    ...securityMeta,
    file: '(protected)/security/page',
    path: '/security',
  },
] as const satisfies readonly WebRouteEntry[]
