// app.config.ts — the single source of every version/identity surface.
// DERIVATION IS THE LOCKSTEP MECHANISM: version, ios.buildNumber and
// android.versionCode are all computed from package.json, so they cannot
// drift; the version-sync gate re-computes the same formulas and asserts
// equality (a consumer replacing them with literals goes red on the next
// bump). eas.json pins appVersionSource: "local" + autoIncrement: false —
// a remote counter would be a version surface no gate can diff.
// SOURCE: docs/harness/README.md (version lockstep doctrine) [corpus: harness/doctrine]
import pkg from './package.json'

const [major = 0, minor = 0, patch = 0] = pkg.version.split('.').map(Number)

// versionCode must ascend monotonically for Play; maj*1e6 + min*1e3 + pat does
// while semver ascends, and stays decodable by eye. The version-sync gate errs
// loudly as minor/patch approach the 999 bound.
const versionCode = major * 1_000_000 + minor * 1_000 + patch

// LOCKSTEP: this hex IS the dark `canvas` token — the OKLCH source in
// packages/design-tokens rendered by that package's generator into
// src/generated/native.ts, which apps/mobile reads through src/theme/theme.ts.
// The native launch frame (splash + adaptive-icon background) must paint the
// same pixel the first React frame paints, or every cold start flashes; the
// expo-policy gate asserts this literal equals the generated token. It cannot
// be an import: app.config.ts is evaluated by the Expo CLI under Node, outside
// the Metro graph, so the value has to be repeated here — and the gate is what
// makes the repetition safe. Change the token, regenerate, and update this
// literal in the same reviewed diff.
// SOURCE: packages/design-tokens/src/generated/native.ts (palettes.dark.canvas)
const CANVAS_DARK = '#090d15'

export default {
  expo: {
    name: '{{PROJECT_NAME}}',
    slug: '{{PROJECT_SLUG}}',
    scheme: '{{APP_SCHEME}}',
    version: pkg.version,
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    newArchEnabled: true,
    // Placeholder marks, generated by a deterministic solid-color PNG script:
    // replace with real art, keep the paths (the build gate resolves them).
    icon: './assets/icon.png',
    // Store identity — locked in tools/identity.lock.json; the expo-policy gate
    // asserts both sides equal the lock. Immutable after first release.
    ios: {
      bundleIdentifier: '{{APP_IDENTIFIER}}',
      buildNumber: pkg.version,
      supportsTablet: true,
      infoPlist: {
        // Export compliance, DECLARED: undeclared re-asks the encryption
        // question on every TestFlight/App Store build. False is correct for
        // this stack — the app's only cryptography is standard TLS (exempt).
        // Flip to true (a reviewed act: tools/store-policy.json iosEncryption)
        // only if you ship non-exempt cryptography.
        // SOURCE: https://developer.apple.com/documentation/bundleresources/information-property-list/itsappusesnonexemptencryption
        ITSAppUsesNonExemptEncryption: false,
      },
    },
    android: {
      package: '{{APP_IDENTIFIER}}',
      versionCode,
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: CANVAS_DARK,
      },
    },
    // OTA compatibility boundary: an update can only reach the exact store
    // version it was exported against. Deterministic and PR-reviewable, unlike
    // the fingerprint policy (a computed hash) — see design record.
    // SOURCE: EAS Update runtime versions — the appVersion policy [corpus: expo/runtime-versions]
    runtimeVersion: { policy: 'appVersion' },
    extra: {
      // The committed transport target — the expo-policy gate asserts it is
      // https or loopback. Never a secret (it ships in the bundle by design).
      // The KEY stays `apiOrigin` (the expo-policy gate reads that name); the
      // VALUE is {{WEB_ORIGIN}} — mobile talks to the web app's own origin,
      // which is also the cookie/CORS origin. See src/lib/trpc/client.ts.
      apiOrigin: '{{WEB_ORIGIN}}',
      eas: {
        projectId: '{{EAS_PROJECT_ID}}',
      },
    },
    plugins: [
      'expo-router',
      'expo-secure-store',
      // Native locale surface (per-app language on iOS; RTL resources).
      'expo-localization',
      // SDK 57 splash config lives on the plugin (the legacy top-level `splash`
      // key is the classic-build path). backgroundColor rides the dark canvas
      // token in BOTH themes deliberately: the dark frame is the anti-flash
      // launch surface (same doctrine as the desktop original's launch frame).
      [
        'expo-splash-screen',
        {
          image: './assets/splash-icon.png',
          imageWidth: 160,
          resizeMode: 'contain',
          backgroundColor: CANVAS_DARK,
        },
      ],
    ],
    experiments: {
      // Opt-in at SDK 57 (enabled in Expo's default template, not at the SDK
      // level) — this template enables it; babel-preset-expo carries the babel
      // plugin as its own dependency, so no extra install.
      reactCompiler: true,
    },
  },
}
