// GENERATED by packages/design-system-native/scripts/gen-preset.mjs — do not edit.
//
// The Tailwind v3 half of the token contract: every value here is emitted from
// @app/design-tokens. Regenerate with
// `pnpm --filter @app/design-system-native run gen`; `gen:check` regen-diffs it.
//
// Add it to the mobile app AFTER nativewind/preset:
//
//   presets: [require('nativewind/preset'), require('@app/design-system-native/tailwind-preset')]
//
// and make sure the app config's `content` globs reach this package — Tailwind only
// emits classes it has SEEN, and it cannot see a component it was never pointed at.

// theme.extend, not theme: replacing the scales wholesale would also delete the
// fractional spacing steps (py-1.5) and every utility this package does not name but
// app code legitimately uses. extend overrides same-named keys and leaves the rest.
module.exports = {
  theme: {
    extend: {
      colors: {
        canvas: 'var(--color-canvas)',
        surface: 'var(--color-surface)',
        edge: 'var(--color-edge)',
        ink: 'var(--color-ink)',
        'ink-muted': 'var(--color-ink-muted)',
        accent: 'var(--color-accent)',
        danger: 'var(--color-danger)',
        success: 'var(--color-success)',
      },
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
        full: '9999px',
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
    },
  },
}
