// The released-sha tables (template/shas/<version>.json) — pure judgements.
//
// `update` may overwrite an owned file only when a RELEASE shipped the bytes it finds
// (installer/lib/provenance.mjs). These are the functions that say what a tree ships, fold
// that into a table, and judge a table against a tree. The I/O — walking commits, writing
// files, the two lane wirings — lives in scripts/generate-released-shas.mjs and
// scripts/check-released-shas.mjs.
//
// A table is a SET per path, and it only grows: the documented install command carries no
// tag, so every first-parent `main` commit that carried a version is a release as far as
// some install is concerned, and bytes that shipped once cannot un-ship.
import { readdirSync } from 'node:fs'
import { join } from 'node:path'
import { sha256 } from '../../installer/lib/manifest.mjs'
import { tokenSites } from '../../installer/lib/placeholders.mjs'

/** @typedef {{ sha256: string, sites?: Array<[number, string]> }} Variant */
/** @typedef {Record<string, Variant[]>} OwnedMap install path → variants */
/** @typedef {{ '//': string, version: string, files: OwnedMap }} Table */

const TABLE_NOTE =
  'GENERATED by scripts/generate-released-shas.mjs — never typed. Per OWNED install path, every byte-variant a first-parent main commit (or the tag) carrying this version shipped: sha256 over the template SOURCE with tokens intact, plus the token sites of a placeholder-bearing file. installer/lib/provenance.mjs reads it to tell a file a release shipped from a fork whose sha was re-recorded. It only grows.'

/**
 * Every template tree that can hold an installable file: base, each module, stack, each
 * design-token preset. Stack and presets are seeded almost everywhere — almost: one owned
 * file lives under stack, and a walk that skipped it would park that file forever.
 *
 * @param {string} templateDir absolute path of a `template/` directory
 */
export function templateTrees(templateDir) {
  /** @param {string} sub */
  const dirs = (sub) => {
    try {
      return readdirSync(join(templateDir, sub), { withFileTypes: true })
        .filter((e) => e.isDirectory())
        .map((e) => `${sub}/${e.name}`)
        .sort()
    } catch {
      return [] // a commit older than the directory
    }
  }
  return ['base', ...dirs('modules'), 'stack', ...dirs('presets')]
}

/** @param {Variant[]} variants @param {Variant} variant */
function addVariant(variants, variant) {
  if (variants.some((v) => v.sha256 === variant.sha256)) return
  variants.push(variant)
  variants.sort((a, b) => (a.sha256 < b.sha256 ? -1 : 1))
}

/**
 * What one tree of commits ships, per owned install path. The walker functions are
 * PARAMETERS: a historical commit is judged by ITS OWN walkTemplate / renderEntry /
 * fileMode, because the seeded lists and the dotless renames moved between releases and a
 * table computed with today's rules would describe an install nobody ever had.
 *
 * `renderEntry(entry, {})` rather than a raw read: with no answers every token is left
 * intact, so this is byte-for-byte what the installer writes before substitution (and a
 * Buffer, verbatim, for a binary asset).
 *
 * @param {{ trees: string[],
 *           walkTemplate: (tree: string) => Array<{ installPath: string, sourcePath: string }>,
 *           renderEntry: (entry: { sourcePath: string }, answers: Record<string, never>) => string | Buffer,
 *           fileMode: (installPath: string) => string }} walker
 * @returns {OwnedMap}
 */
export function ownedMap({ trees, walkTemplate, renderEntry, fileMode }) {
  /** @type {OwnedMap} */
  const map = {}
  for (const tree of trees) {
    for (const entry of walkTemplate(tree)) {
      if (fileMode(entry.installPath) !== 'owned') continue
      const source = renderEntry(entry, {})
      /** @type {Variant} */
      const variant = { sha256: sha256(source) }
      const sites = typeof source === 'string' ? tokenSites(source) : []
      if (sites.length > 0) variant.sites = sites
      addVariant((map[entry.installPath] ??= []), variant)
    }
  }
  return map
}

/**
 * Fold an owned map into a table — additive, never subtractive — and return it with its
 * paths sorted. A null table is a version seen for the first time.
 *
 * @param {Table | null} table @param {string} version @param {OwnedMap} map
 * @returns {Table}
 */
export function unionInto(table, version, map) {
  /** @type {OwnedMap} */
  const files = {}
  for (const [path, variants] of Object.entries(table?.files ?? {})) files[path] = variants.map((v) => ({ ...v }))
  for (const [path, variants] of Object.entries(map)) {
    for (const variant of variants) addVariant((files[path] ??= []), variant)
  }
  const sorted = Object.fromEntries(Object.entries(files).sort(([a], [b]) => (a < b ? -1 : 1)))
  return { '//': TABLE_NOTE, version, files: sorted }
}

/**
 * Every (path, variant) of `map` that `table` does not carry — the closure both lanes
 * assert: the LIVE tree must be inside the current version's table, and a TAG's tree
 * inside its version's.
 *
 * @param {OwnedMap} map @param {Table | null} table @param {string} label what `map` is
 * @returns {string[]} problems, empty when closed
 */
export function missingFrom(map, table, label) {
  if (table === null) return [`${label}: no released-sha table exists for it at all`]
  const problems = []
  for (const [path, variants] of Object.entries(map)) {
    for (const variant of variants) {
      if (!(table.files[path] ?? []).some((v) => v.sha256 === variant.sha256)) {
        problems.push(`${label}: ${path} ships sha256 ${variant.sha256.slice(0, 12)}… and template/shas/${table.version}.json does not list it`)
      }
    }
  }
  return problems
}

/**
 * Shape lint for one table as parsed from disk. The `{{` rule is not pedantry: hygiene's
 * placeholder closure scans everything under template/, so a token written in its braced
 * form inside a table would be read as a template token with no registry entry.
 *
 * @param {string} file the file name, `<version>.json` @param {unknown} parsed @param {string} rawText
 * @returns {string[]}
 */
export function lintTable(file, parsed, rawText) {
  const table = /** @type {Partial<Table> | null} */ (parsed)
  if (table === null || typeof table !== 'object' || typeof table.files !== 'object' || table.files === null) {
    return [`${file}: not a { version, files } table`]
  }
  const problems = []
  if (`${String(table.version)}.json` !== file) problems.push(`${file}: its "version" field says ${String(table.version)}`)
  if (rawText.includes('{{')) problems.push(`${file}: carries a braced token — sites hold BARE token names only`)
  const paths = Object.keys(table.files)
  if (paths.join('\n') !== [...paths].sort().join('\n')) problems.push(`${file}: paths are not sorted — regenerate, never hand-edit`)
  for (const [path, variants] of Object.entries(table.files)) {
    const shas = (Array.isArray(variants) ? variants : []).map((v) => v?.sha256)
    if (shas.length === 0 || shas.some((s) => typeof s !== 'string' || !/^[0-9a-f]{64}$/.test(s))) {
      problems.push(`${file}: ${path} has no variants, or a variant without a sha256`)
    } else if (shas.join('\n') !== [...new Set(shas)].sort().join('\n')) {
      problems.push(`${file}: ${path} variants are duplicated or unsorted — regenerate, never hand-edit`)
    }
  }
  return problems
}

/**
 * Versions that must have a table and do not: every released vintage, plus the version
 * being built — the closure that makes "add the predecessor to VINTAGES" and "start the
 * next table" one act at a version bump instead of a thing to remember.
 *
 * @param {string[]} vintages @param {string} pkgVersion @param {string[]} present versions with a table
 */
export function missingVersions(vintages, pkgVersion, present) {
  const have = new Set(present)
  return [...new Set([...vintages, pkgVersion])].filter((v) => !have.has(v))
}
