// The released-sha tables (template/shas/<version>.json) — pure judgements.
//
// `update` may overwrite an owned file only when a RELEASE shipped the bytes it finds
// (installer/lib/provenance.mjs). These are the functions that say what a tree ships, fold
// that into a table, and judge a table against a tree. The I/O — walking commits, writing
// files, the two lane wirings — lives in scripts/generate-released-shas.mjs and
// scripts/check-released-shas.mjs.
//
// A table is a SET per path, and it only grows: the documented install command carries no
// tag, so every first-parent `main` commit that carried a version is a release as far as
// some install is concerned, and bytes that shipped once cannot un-ship.
//
// Since 1.1.0 (#84) a table carries TWO maps. `files` is the owned map above, and it is all
// installer/lib/provenance.mjs reads. `planted` lists, per path in today's ESCAPE_LISTS, every
// byte-variant the commit's own template shipped, whatever the path's mode was then. Escape
// lists are seeded, so no `files` entry ever vouched for their bytes, and the tables never
// reach an install. The union of every table's `planted` map is therefore written into the
// template as the OWNED file tools/lib/planted-shas.json, which gate-integrity reads to ask
// whether a harness release planted an untracked escape list, not merely whether its bytes
// match a manifest record anyone can re-record.
import { existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { sha256 } from '../../installer/lib/manifest.mjs'
import { tokenSites } from '../../installer/lib/placeholders.mjs'

/** @typedef {{ sha256: string, sites?: Array<[number, string]> }} Variant */
/** @typedef {Record<string, Variant[]>} OwnedMap install path → variants */
/** @typedef {{ '//': string, version: string, files: OwnedMap, planted: OwnedMap }} Table */
/** @typedef {{ '//': string, files: OwnedMap }} PlantedEvidence tools/lib/planted-shas.json */

const TABLE_NOTE =
  'GENERATED by scripts/generate-released-shas.mjs — never typed. `files`: per OWNED install path, every byte-variant a first-parent main commit (or the tag) carrying this version shipped: sha256 over the template SOURCE with tokens intact, plus the token sites of a placeholder-bearing file. installer/lib/provenance.mjs reads it to tell a file a release shipped from a fork whose sha was re-recorded. `planted` (1.1.0): the same, per escape list (tools/lib/enforcement-surface.mjs ESCAPE_LISTS) the commit shipped, whatever its mode; its union across every table is tools/lib/planted-shas.json. It only grows.'

// The install path of the generated evidence file (template/base/<this>), OWNED and under
// tools/, so gate-integrity's sub-check 1 hash-pins it and `update` plants it in the same run
// that plants a new escape list.
export const PLANTED_INSTALL_PATH = 'tools/lib/planted-shas.json'

const PLANTED_NOTE =
  'GENERATED by scripts/generate-released-shas.mjs from the planted maps of template/shas/*.json — never typed, never edited in an install. Per escape list, every byte-variant a harness release planted: sha256 over the template SOURCE with tokens intact, plus the token sites of a placeholder-bearing file (derendered with the manifest answers before comparing). tools/check-gate-integrity.mjs reads it: an untracked escape list is a harness plant only when its bytes match the manifest record AND a variant here explains them.'

/**
 * Every template tree that can hold an installable file: base, each module, stack, each
 * design-token preset, and the worked example (2.0.0, #85: `init --with-demo`). Stack,
 * presets and demo are seeded almost everywhere — almost: owned files live under stack and
 * under demo (the example's Maestro flow and journey), and a walk that skipped one would
 * park that file forever.
 *
 * @param {string} templateDir absolute path of a `template/` directory
 */
export function templateTrees(templateDir) {
  /** @param {string} sub */
  const dirs = (sub) => {
    try {
      return readdirSync(join(templateDir, sub), { withFileTypes: true })
        .filter((e) => e.isDirectory())
        .map((e) => `${sub}/${e.name}`)
        .sort()
    } catch {
      return [] // a commit older than the directory
    }
  }
  const demo = existsSync(join(templateDir, 'demo')) ? ['demo'] : [] // a commit older than 2.0.0
  return ['base', ...dirs('modules'), 'stack', ...dirs('presets'), ...demo]
}

/** @param {Variant[]} variants @param {Variant} variant */
function addVariant(variants, variant) {
  if (variants.some((v) => v.sha256 === variant.sha256)) return
  variants.push(variant)
  variants.sort((a, b) => (a.sha256 < b.sha256 ? -1 : 1))
}

/** One template source, tokens intact, as a variant: its sha, and its token sites if any. */
/** @param {string | Buffer} source @returns {Variant} */
function variantOf(source) {
  /** @type {Variant} */
  const variant = { sha256: sha256(source) }
  const sites = typeof source === 'string' ? tokenSites(source) : []
  if (sites.length > 0) variant.sites = sites
  return variant
}

/**
 * What one tree of commits ships, per owned install path. The walker functions are
 * PARAMETERS: a historical commit is judged by ITS OWN walkTemplate / renderEntry /
 * fileMode, because the seeded lists and the dotless renames moved between releases and a
 * table computed with today's rules would describe an install nobody ever had.
 *
 * `renderEntry(entry, {})` rather than a raw read: with no answers every token is left
 * intact, so this is byte-for-byte what the installer writes before substitution (and a
 * Buffer, verbatim, for a binary asset).
 *
 * @param {{ trees: string[],
 *           walkTemplate: (tree: string) => Array<{ installPath: string, sourcePath: string }>,
 *           renderEntry: (entry: { sourcePath: string }, answers: Record<string, never>) => string | Buffer,
 *           fileMode: (installPath: string) => string }} walker
 * @returns {OwnedMap}
 */
export function ownedMap({ trees, walkTemplate, renderEntry, fileMode }) {
  /** @type {OwnedMap} */
  const map = {}
  for (const tree of trees) {
    for (const entry of walkTemplate(tree)) {
      if (fileMode(entry.installPath) !== 'owned') continue
      addVariant((map[entry.installPath] ??= []), variantOf(renderEntry(entry, {})))
    }
  }
  return map
}

/**
 * What one tree of commits PLANTS, per escape list (1.1.0, #84): every entry whose install
 * path is in `paths`, whatever `fileMode` said at that commit — some escape lists were owned
 * before they became seeded, and an install planted their bytes either way. `paths` is
 * TODAY's ESCAPE_LISTS, so a list added later is found in every older tree that shipped it.
 * The walker is the commit's own, for the reason ownedMap gives.
 *
 * @param {{ trees: string[],
 *           walkTemplate: (tree: string) => Array<{ installPath: string, sourcePath: string }>,
 *           renderEntry: (entry: { sourcePath: string }, answers: Record<string, never>) => string | Buffer,
 *           paths: readonly string[] }} walker
 * @returns {OwnedMap}
 */
export function plantedMap({ trees, walkTemplate, renderEntry, paths }) {
  const wanted = new Set(paths)
  /** @type {OwnedMap} */
  const map = {}
  for (const tree of trees) {
    for (const entry of walkTemplate(tree)) {
      if (!wanted.has(entry.installPath)) continue
      addVariant((map[entry.installPath] ??= []), variantOf(renderEntry(entry, {})))
    }
  }
  return map
}

/** @param {OwnedMap | undefined} base @param {OwnedMap} add @returns {OwnedMap} sorted copy */
function foldMap(base, add) {
  /** @type {OwnedMap} */
  const out = {}
  for (const [path, variants] of Object.entries(base ?? {})) out[path] = variants.map((v) => ({ ...v }))
  for (const [path, variants] of Object.entries(add)) {
    for (const variant of variants) addVariant((out[path] ??= []), variant)
  }
  return Object.fromEntries(Object.entries(out).sort(([a], [b]) => (a < b ? -1 : 1)))
}

/**
 * Fold an owned map, and a planted map, into a table — additive, never subtractive — and
 * return it with its paths sorted. A null table is a version seen for the first time; a
 * table from before 1.1.0 gains an empty `planted` map until a planted map is folded in.
 *
 * @param {Table | null} table @param {string} version @param {OwnedMap} map
 * @param {OwnedMap} [planted]
 * @returns {Table}
 */
export function unionInto(table, version, map, planted = {}) {
  return { '//': TABLE_NOTE, version, files: foldMap(table?.files, map), planted: foldMap(table?.planted, planted) }
}

/**
 * The evidence an install reads: the union of every table's `planted` map.
 *
 * @param {Iterable<Pick<Table, 'planted'>>} tables
 * @returns {PlantedEvidence}
 */
export function plantedUnion(tables) {
  /** @type {OwnedMap} */
  let files = {}
  for (const table of tables) files = foldMap(files, table.planted ?? {})
  return { '//': PLANTED_NOTE, files }
}

/**
 * tools/lib/planted-shas.json's exact bytes. The file lives under template/base, where the
 * scaffold's formatter (biome, lineWidth 100) runs over every JSON file, so it is written the
 * way that formatter writes it: two-space objects with one key per line, and each `sites`
 * array on one line while it fits (a placeholder-bearing escape list carries a handful of
 * short [offset, token] pairs), one pair per line when it does not. JSON.stringify alone
 * would put every offset on a line of its own and red the scaffold's format check on a file
 * nobody may edit.
 *
 * @param {PlantedEvidence} evidence
 */
export function plantedFileText(evidence) {
  const paths = Object.keys(evidence.files)
  if (paths.length === 0) return `{\n  "//": ${JSON.stringify(evidence['//'])},\n  "files": {}\n}\n`
  const blocks = paths.map((path) => {
    const variants = evidence.files[path].map((v) => {
      const fields = [`        "sha256": ${JSON.stringify(v.sha256)}`]
      if (v.sites) fields.push(`        "sites": ${sitesText(v.sites)}`)
      return `      {\n${fields.join(',\n')}\n      }`
    })
    return `    ${JSON.stringify(path)}: [\n${variants.join(',\n')}\n    ]`
  })
  return `{\n  "//": ${JSON.stringify(evidence['//'])},\n  "files": {\n${blocks.join(',\n')}\n  }\n}\n`
}

/** @param {Array<[number, string]>} sites */
function sitesText(sites) {
  const pairs = sites.map(([offset, token]) => `[${String(offset)}, ${JSON.stringify(token)}]`)
  const inline = `[${pairs.join(', ')}]`
  if (`        "sites": ${inline}`.length <= 100) return inline
  return `[\n${pairs.map((p) => `          ${p}`).join(',\n')}\n        ]`
}

/**
 * Every (path, variant) of `map` that `table` does not carry — the closure both lanes
 * assert: the LIVE tree must be inside the current version's table, and a TAG's tree
 * inside its version's. `field` picks the owned map (`files`) or the escape lists
 * (`planted`, 1.1.0).
 *
 * @param {OwnedMap} map @param {Table | null} table @param {string} label what `map` is
 * @param {'files' | 'planted'} [field]
 * @returns {string[]} problems, empty when closed
 */
export function missingFrom(map, table, label, field = 'files') {
  if (table === null) return [`${label}: no released-sha table exists for it at all`]
  const listed = table[field] ?? {}
  const [verb, where] = field === 'files' ? ['ships', ''] : ['plants', ' under planted']
  const problems = []
  for (const [path, variants] of Object.entries(map)) {
    for (const variant of variants) {
      if (!(listed[path] ?? []).some((v) => v.sha256 === variant.sha256)) {
        problems.push(`${label}: ${path} ${verb} sha256 ${variant.sha256.slice(0, 12)}… and template/shas/${table.version}.json does not list it${where}`)
      }
    }
  }
  return problems
}

/**
 * Shape lint for one table as parsed from disk. The `{{` rule is not pedantry: hygiene's
 * placeholder closure scans everything under template/, so a token written in its braced
 * form inside a table would be read as a template token with no registry entry.
 *
 * @param {string} file the file name, `<version>.json` @param {unknown} parsed @param {string} rawText
 * @returns {string[]}
 */
export function lintTable(file, parsed, rawText) {
  const table = /** @type {Partial<Table> | null} */ (parsed)
  if (table === null || typeof table !== 'object' || typeof table.files !== 'object' || table.files === null) {
    return [`${file}: not a { version, files } table`]
  }
  const problems = []
  if (`${String(table.version)}.json` !== file) problems.push(`${file}: its "version" field says ${String(table.version)}`)
  if (rawText.includes('{{')) problems.push(`${file}: carries a braced token — sites hold BARE token names only`)
  problems.push(...lintMap(file, '', table.files))
  // 1.1.0 (#84): every table carries the escape lists its commits planted. `--all` backfilled
  // them from the lineage floor up, so a table without one was hand-edited or never regenerated.
  if (typeof table.planted !== 'object' || table.planted === null || Array.isArray(table.planted)) {
    problems.push(`${file}: has no planted map — run \`node scripts/generate-released-shas.mjs --all\``)
  } else {
    problems.push(...lintMap(file, 'planted ', table.planted))
  }
  return problems
}

/**
 * The shape rules one map of a table obeys: sorted paths, and per path a non-empty, sorted,
 * duplicate-free list of sha256 variants.
 *
 * @param {string} file @param {string} which '' for `files`, 'planted ' for `planted`
 * @param {Record<string, unknown>} map
 * @returns {string[]}
 */
function lintMap(file, which, map) {
  const problems = []
  const paths = Object.keys(map)
  if (paths.join('\n') !== [...paths].sort().join('\n')) problems.push(`${file}: ${which}paths are not sorted — regenerate, never hand-edit`)
  for (const [path, variants] of Object.entries(map)) {
    const shas = (Array.isArray(variants) ? variants : []).map((v) => v?.sha256)
    if (shas.length === 0 || shas.some((s) => typeof s !== 'string' || !/^[0-9a-f]{64}$/.test(s))) {
      problems.push(`${file}: ${which}${path} has no variants, or a variant without a sha256`)
    } else if (shas.join('\n') !== [...new Set(shas)].sort().join('\n')) {
      problems.push(`${file}: ${which}${path} variants are duplicated or unsorted — regenerate, never hand-edit`)
    }
  }
  return problems
}

/**
 * Versions that must have a table and do not: every released vintage, plus the version
 * being built — the closure that makes "add the predecessor to VINTAGES" and "start the
 * next table" one act at a version bump instead of a thing to remember.
 *
 * @param {string[]} vintages @param {string} pkgVersion @param {string[]} present versions with a table
 */
export function missingVersions(vintages, pkgVersion, present) {
  const have = new Set(present)
  return [...new Set([...vintages, pkgVersion])].filter((v) => !have.has(v))
}
