import {
  FONT_WEIGHTS,
  RADIUS_STEPS,
  SEMANTIC_TOKENS,
  SPACE_STEPS,
  type SemanticToken,
  TYPE_STEPS,
  fontWeight,
  radius,
  space,
  typeScale,
} from '@app/design-tokens'

// The Tailwind v3 preset, rendered from the tokens.
//
// WHY THIS EXISTS AT ALL. NativeWind 4 requires Tailwind v3, so class VALUES on this
// platform come from a JS config object rather than from a CSS `@theme` block — and
// the v3 defaults are not the token ramp. `rounded-sm` is 2px in v3 and 4px in the v4
// scale the web side uses; `text-base` happens to agree; `p-4` happens to agree.
// "Happens to agree" is not a design system. This preset re-pins every scale a
// component here names, so the same class means the same measurement on both surfaces.
//
// WHY IT IS GENERATED RATHER THAN HAND-WRITTEN. Thirty-odd numbers copied out of the
// token module is thirty-odd chances for the copy to go a month stale, and nothing
// about a stale copy looks wrong — the app simply renders last month's spacing. The
// committed tailwind-preset.cjs is emitted from here and regen-diffed by
// preset.test.ts (and by `pnpm --filter @app/design-system-native run gen:check`),
// exactly like the two artifacts in @app/design-tokens.
//
// WHY THE GENERATOR LIVES IN THIS PACKAGE RATHER THAN IN THE TOKEN PACKAGE. A
// NativeWind preset is this package's platform adapter; the token package stays
// framework-neutral and the dependency arrow stays design-system-native →
// design-tokens.
//
// WHY CommonJS. Tailwind v3 loads presets through a `require` from the app's
// tailwind.config.js. An ESM or TypeScript preset resolves only when the config loader
// happens to be jiti-backed, which is an implementation detail of a tool this package
// does not control.

const COLOR_VAR_PREFIX = '--color-'

/**
 * The CSS variable that carries a semantic token's value at runtime.
 *
 * Colours are indirected through variables rather than baked into the preset because a
 * class string compiles ONCE and both themes have to be reachable from it.
 * ThemeProvider injects the active theme's hex with NativeWind's `vars()`, so
 * `bg-canvas` re-resolves on a theme change without recompiling a single class.
 *
 * The alpha-modifier form (`rgb(var(--x) / <alpha-value>)`) is deliberately NOT used:
 * it needs the variable to hold a bare channel triplet, which would mean shipping every
 * colour twice — as hex for the RN APIs that need a colour string, and as channels for
 * Tailwind. `bg-canvas/50` therefore does not work here; a translucent surface is a
 * token, not a modifier.
 */
export function colorVarName(token: SemanticToken): string {
  return `${COLOR_VAR_PREFIX}${token}`
}

// Bare where a JS object literal allows it, quoted otherwise — the exact shape Biome's
// `asNeeded` quoting produces. Emitting a quote it would strip turns the next format
// pass into permanent regen drift.
const BARE_KEY = /^(?:[A-Za-z_$][\w$]*|\d+)$/
function key(name: string): string {
  return BARE_KEY.test(name) ? name : `'${name}'`
}

function px(value: number): string {
  return `${value}px`
}

function emitColors(lines: string[]): void {
  lines.push('colors: {')
  for (const token of SEMANTIC_TOKENS) {
    lines.push(`  ${key(token)}: 'var(${colorVarName(token)})',`)
  }
  lines.push('},')
}

function emitSpacing(lines: string[]): void {
  lines.push('spacing: {')
  for (const step of SPACE_STEPS) {
    lines.push(`  ${key(String(step))}: '${px(space[step])}',`)
  }
  lines.push('},')
}

function emitRadius(lines: string[]): void {
  lines.push('borderRadius: {')
  for (const step of RADIUS_STEPS) {
    lines.push(`  ${key(step)}: '${px(radius[step])}',`)
  }
  lines.push('},')
}

function emitTypography(lines: string[]): void {
  lines.push('fontSize: {')
  for (const step of TYPE_STEPS) {
    const { fontSize, lineHeight } = typeScale[step]
    lines.push(`  ${key(step)}: ['${px(fontSize)}', { lineHeight: '${px(lineHeight)}' }],`)
  }
  lines.push('},', 'fontWeight: {')
  for (const name of FONT_WEIGHTS) {
    lines.push(`  ${key(name)}: '${fontWeight[name]}',`)
  }
  lines.push('},')
}

const PRESET_HEADER = [
  '// GENERATED by packages/design-system-native/scripts/gen-preset.mjs — do not edit.',
  '//',
  '// The Tailwind v3 half of the token contract: every value here is emitted from',
  '// @app/design-tokens. Regenerate with',
  '// `pnpm --filter @app/design-system-native run gen`; `gen:check` regen-diffs it.',
  '//',
  '// Add it to the mobile app AFTER nativewind/preset:',
  '//',
  "//   presets: [require('nativewind/preset'), require('@app/design-system-native/tailwind-preset')]",
  '//',
  "// and make sure the app config's `content` globs reach this package — Tailwind only",
  '// emits classes it has SEEN, and it cannot see a component it was never pointed at.',
  '',
  '// theme.extend, not theme: replacing the scales wholesale would also delete the',
  '// fractional spacing steps (py-1.5) and every utility this package does not name but',
  '// app code legitimately uses. extend overrides same-named keys and leaves the rest.',
  'module.exports = {',
  '  theme: {',
  '    extend: {',
]

/** The committed bytes of tailwind-preset.cjs. Pure: same tokens, same string. */
export function renderPreset(): string {
  const body: string[] = []
  emitColors(body)
  emitSpacing(body)
  emitRadius(body)
  emitTypography(body)

  const lines = [...PRESET_HEADER, ...body.map((line) => `      ${line}`), '    },', '  },', '}']
  return `${lines.join('\n')}\n`
}
