import { useLocalSearchParams } from 'expo-router'
import { View } from 'react-native'
import { AppText } from '../src/components/AppText'
import { OptionRow } from '../src/components/OptionRow'
import { Screen } from '../src/components/Screen'
import { rankCommands } from '../src/features/actions/fuzzyScore'
import { ACTION_COMMANDS } from '../src/features/actions/registry'
import { useI18n } from '../src/i18n'
import { type ProbeControls, parseProbeBudgets, usePerfProbes } from '../src/lib/perf-probes'
import { type Palette, useThemedStyles } from '../src/theme/theme'

// The dev perf-harness screen — the on-device consumer of tools/interaction-budget.json.
//
// CHROME, not content (tools/route-allowlist.json): no data states, dev builds only. The
// CI device lane deep-links here (`{{APP_SCHEME}}://perf-harness?tabSwitchMs=...`, params
// generated by tools/check-e2e-device.mjs from the budget file), the screen SELF-MEASURES
// against those caps through the real workload (the actions registry ranked by
// rankCommands, rendered through the shipped row primitives), and the verdict surfaces as
// a leaf testID Maestro asserts: `perf-pass` (all budgets held) or `perf-fail` (each
// breach rendered through the catalog). Self-measurement keeps the lane's assertion ONE
// visibility check — the wall-clock noise lives in the medians, not in the driver.
//
// Dev-only ON PURPOSE: a release binary must not ship a self-benchmarking surface, so
// outside __DEV__ the screen renders only its unavailability note (`perf-unavailable`) —
// a lane pointed at the wrong build fails loudly on the missing marker.
// SOURCE: docs/harness/gates-catalog.md (CI-only lanes — the device lane) [corpus: harness/doctrine]

const perfStyles = (_palette: Palette) => ({
  workload: {
    // Off-screen on purpose: the probes price render commits, not pixels the
    // operator needs to see; opacity keeps the subtree composited for real.
    opacity: 0,
  },
})

/** The probe workload: the REAL modal ranking over catalog-resolved titles. */
function Workload({ step, titles }: { readonly step: number; readonly titles: readonly string[] }) {
  const styles = useThemedStyles(perfStyles)
  // Queries derive from the titles themselves (never literal copy): each step
  // re-ranks on a different prefix, so every commit prices a fresh ranking.
  const source = titles[step % titles.length] ?? ''
  const query = source.slice(0, (step % 3) + 1)
  const commands = ACTION_COMMANDS.map((command, index) => ({
    id: command.id,
    title: titles[index] ?? command.id,
  }))
  const ranked = rankCommands(query, commands)
  const asRows = step % 2 === 0
  return (
    <View style={styles.workload} aria-hidden>
      {asRows
        ? ranked.map((command) => (
            <OptionRow key={command.id} label={command.title} onPress={() => undefined} />
          ))
        : ranked.map((command) => <AppText key={command.id}>{command.title}</AppText>)}
    </View>
  )
}

function Verdict({ controls }: { readonly controls: ProbeControls }) {
  const { t } = useI18n()
  if (controls.report === null) {
    return (
      <AppText variant="muted" testID="perf-running">
        {t('perf.running')}
      </AppText>
    )
  }
  if (controls.report.pass) {
    return (
      <AppText variant="muted" testID="perf-pass">
        {t('perf.pass')}
      </AppText>
    )
  }
  return (
    <View>
      <AppText variant="danger" role="alert" testID="perf-fail">
        {t('perf.fail')}
      </AppText>
      {controls.report.failures.map((failure) => (
        <AppText key={failure.metric} variant="muted">
          {t('perf.over', {
            metric: failure.metric,
            measured: Math.round(failure.measured),
            cap: failure.cap,
          })}
        </AppText>
      ))}
    </View>
  )
}

function DevPerfHarness() {
  const { t } = useI18n()
  const params = useLocalSearchParams<{
    tabSwitchMs?: string
    actionsOpenMs?: string
    frameDropMax?: string
    runs?: string
  }>()
  // Rebuilt as a literal so the object satisfies the parser's index-signature
  // parameter (router param types carry none of their own).
  const controls = usePerfProbes(
    parseProbeBudgets({
      tabSwitchMs: params.tabSwitchMs,
      actionsOpenMs: params.actionsOpenMs,
      frameDropMax: params.frameDropMax,
      runs: params.runs,
    }),
  )
  const titles = ACTION_COMMANDS.map((command) => t(command.titleKey))
  return (
    <Screen testID="perf-harness-screen">
      <AppText variant="title">{t('perf.title')}</AppText>
      <Verdict controls={controls} />
      {controls.phase !== 'done' && <Workload step={controls.step} titles={titles} />}
    </Screen>
  )
}

export default function PerfHarnessScreen() {
  const { t } = useI18n()
  if (!__DEV__) {
    return (
      <Screen testID="perf-harness-screen">
        <AppText variant="title">{t('perf.title')}</AppText>
        <AppText variant="muted" testID="perf-unavailable">
          {t('perf.unavailable')}
        </AppText>
      </Screen>
    )
  }
  return <DevPerfHarness />
}
